In [1]:
from urbansim.models.dcm import MNLDiscreteChoiceModel

import os
import numpy as np
import pandas as pd

import orca
from urbansim.utils import misc

import dataset
import variables
import models
import utils

orca.run(["build_networks"])
orca.run(["neighborhood_vars"])

using seed 271828
Running step 'build_networks'
Time to execute step 'build_networks': 121.13 s
Total time to execute iteration 1 with iteration value None: 121.24 s
Running step 'neighborhood_vars'
Computing accessibility variables
Computing log_sum_residential_units

C:\Users\Juan\Anaconda3\envs\semcog_py2\lib\site-packages\urbansim\utils\networks.py:18: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(open(misc.config(cfgname)))

Computing ave_lot_sqft
Computing log_sum_nonresidential_units
Computing population
Computing households
Computing midinc_hhs
Computing lowinc_hhs
Computing highinc_hhs
Computing race_1_hhs
Computing race_2_hhs
Computing race_3_hhs
Computing race_4_hhs
Computing hhs_with_children
Computing hhsize
Computing ave_income
Computing max_industrial_far
Computing max_office_far
Computing max_retail_far
Computing max_medical_far
Computing jobs
Computing retail_jobs
Computing node_r1500_sqft
Computing residential
Computing ave_nonres_sqft_price
Computing retail
Computing office
Computing industrial
Computing medical
Computing quarter_mile_to_transit
Computing log_15min_retail_jobs
Computing log_15min_shopping_jobs
Computing log_30min_retail_jobs
Computing log_30min_shopping_jobs
Computing accessibility variables
Computing log_sum_30min_jobs
Computing log_sum_45min_jobs
Computing log_sum_60min_jobs
Computing log_sum_10min_pop
Computing log_sum_20min_pop
Computing log_sum_15min_retail_jobs
Computing log_sum_15min_shopping_jobs
Computing log_sum_30min_retail_jobs
Computing log_sum_30min_shopping_jobs
Computing elem_school_perf
Time to execute step 'neighborhood_vars': 2599.01 s
Total time to execute iteration 1 with iteration value None: 2599.03 s

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [12]:
# Getting all the variables from the hcl clustvars models
import yaml
import os
path = 'configs/lcm_regional_accessvars/hlcm/'
hlcm_files = os.listdir(path)
hlcm_vars = []
for filen in hlcm_files:
    with open(path + filen) as f:
        store = yaml.safe_load(f)
        hlcm_vars.extend(store['model_expression'])
path = 'configs/lcm_regional_accessvars/elcm/'
elcm_files = os.listdir(path)
for filen in elcm_files:
    with open(path + filen) as f:
        store = yaml.safe_load(f)
        hlcm_vars.extend(store['model_expression'])
hlcm_vars = set(hlcm_vars)

In [13]:
# Alternatives and choosers
hlcm_vars2 = list(hlcm_vars) + ['residential_units', 'vacant_residential_units', 'zone_id', 'mode_income_quartile', 'parcel_id']
alternatives = orca.get_table('buildings').to_frame(hlcm_vars2)
choosers = orca.get_table('households').to_frame(['building_id', 'household_type'])

In [17]:
len(alternatives.columns) - len(hlcm_vars2)

-21

In [18]:
[x for x in alternatives.columns if 'st_nodes_' in x]

[]

In [66]:
[x for x in orca.get_table('buildings').columns if "st_nodes" in x]

[]

In [67]:
[x for x in orca.get_table('buildings').columns if "st_walk" in x]

['st_walk_nearest_park',
 'st_walk_nearest_hospital',
 'st_walk_nearest_grocery',
 'st_walk_nearest_healthcenter',
 'st_walk_nearest_urgentcare',
 'st_walk_nearest_library']

In [62]:
[x for x in orca.get_table('buildings').columns if "st_walk" in x]

['st_walk_nearest_park',
 'st_walk_nearest_hospital',
 'st_walk_nearest_grocery',
 'st_walk_nearest_healthcenter',
 'st_walk_nearest_urgentcare',
 'st_walk_nearest_library']

In [61]:
orca.get_table('buildings').to_frame(['nodes_walk_ave_lot_sqft'])

Disaggregating ave_lot_sqft to buildings from nodes_walk

             nodes_walk_ave_lot_sqft
building_id
1184091                     9.538187
1183390                     7.317530
1183392                     7.317530
1183409                     7.317530
1636985                    12.384972
1183492                     7.951515
1183506                     7.951515
1183608                     7.951515
1183357                     7.951515
1190061                    10.871630
1190092                    10.872358
1190142                    10.871630
1903849                     8.574669
1185212                     9.941387
1414827                    10.482287
1184994                    10.482287
1185329                    10.482287
1185629                    10.482287
1414826                    10.482287
1184492                    10.246005
1184810                    10.246005
1184830                    10.246005
1184863                    10.246005
1184930                    10.246005
1184510                     7.617655
1184544                     7.617655
1047753                     8.022211
1636114                     8.022211
1184177                     7.935862
1184312                     8.014094
...                              ...
8210242                     7.477591
8208663                     7.472931
8210226                     7.472931
8210762                     7.472931
8211071                     7.835857
8209908                     7.835857
8210503                     7.472931
8210296                     7.472931
8211564                     7.596965
8211439                     7.596965
8211221                     7.596965
8210703                     7.615742
8210796                     7.615742
8212826                     7.597188
8212365                     7.721583
8212274                     7.613750
8212017                     7.613750
8211847                     7.596965
8211304                     7.583934
8211731                     7.583934
8210613                     7.472931
8211565                     7.583934
8210929                     7.583934
8211047                     7.583934
8211245                     7.583934
8210454                     7.472931
8211129                     7.835857
8210986                     7.835857
8210786                     7.488411
8210677                     7.488411

[1660654 rows x 1 columns]

In [49]:
store = orca.get_injectable('store')
store['households']

,age_of_head,large_area_id,cars,workers,persons,race_id,income,building_id,children
930000000,42.0,93.0,2,1,5,1,112773.650000,7116155,3.0
930000001,36.0,93.0,2,2,5,1,114083.105000,7114247,3.0
930000002,38.0,93.0,2,1,5,1,119131.030000,7115505,3.0
930000003,40.0,93.0,2,1,4,1,123025.800000,7115305,3.0
930000004,44.0,93.0,3,1,5,1,102977.670000,7116760,3.0
930000005,36.0,93.0,2,1,5,1,114083.105000,7115946,3.0
930000006,44.0,93.0,2,1,4,1,128771.280000,7114147,2.0
930000007,40.0,93.0,2,1,4,1,180227.520000,7116380,1.0
930000008,39.0,93.0,3,1,4,1,382482.848000,7917425,2.0
930000009,43.0,93.0,4,2,4,1,209993.680000,7113873,1.0
930000010,40.0,93.0,2,1,4,1,180227.520000,7116853,2.0
930000011,44.0,93.0,2,1,4,1,134136.750000,7116197,2.0
930000012,25.0,93.0,3,1,1,1,128771.280000,7110340,0.0
930000013,44.0,93.0,4,1,3,1,138711.589500,7113816,0.0
930000014,30.0,93.0,2,1,3,1,137356.032000,7116586,1.0
930000015,44.0,93.0,2,2,3,1,362705.772000,7113176,1.0
930000016,29.0,93.0,2,1,2,1,109035.180000,7112225,1.0
930000017,35.0,93.0,2,1,3,1,103546.715000,7115223,1.0
930000018,44.0,93.0,2,1,3,1,362705.772000,7112511,1.0
930000019,38.0,93.0,2,2,5,1,110733.472150,7114088,3.0
930000020,43.0,93.0,2,2,5,1,343390.080000,7116244,1.0
930000021,36.0,93.0,2,2,5,1,163552.770000,7116854,3.0
930000022,39.0,93.0,3,2,5,1,108471.207928,7116016,3.0
930000023,44.0,93.0,3,3,5,1,123265.106400,7113217,2.0
930000024,39.0,93.0,3,2,5,1,126198.125000,7115607,2.0
930000025,36.0,93.0,3,2,5,1,120240.835600,7116187,3.0
930000026,40.0,93.0,2,2,5,1,151731.820000,7114568,2.0
930000027,43.0,93.0,3,3,5,1,149588.841600,7115822,3.0
930000028,43.0,93.0,3,3,5,1,149588.841600,7115574,2.0
930000029,34.0,93.0,2,2,5,1,118149.152000,7116805,2.0
...,...,...,...,...,...,...,...,...,...
1630698355,62.0,161.0,1,1,2,1,218575.838000,4068509,1.0
1630698347,22.0,161.0,2,1,2,1,91770.976000,4063447,1.0
1630698335,23.0,161.0,1,1,2,1,48460.080000,4061216,0.0
1630698370,64.0,161.0,1,0,2,1,79500.361600,4072766,1.0
1630698395,55.0,161.0,2,2,2,1,93294.565000,4071930,0.0
1630698362,45.0,161.0,1,1,2,1,40383.400000,4072328,0.0
1630698336,23.0,161.0,2,0,1,1,175987.416000,4070388,0.0
1630698389,46.0,161.0,1,1,1,1,26153.234650,4080891,0.0
1630698334,62.0,161.0,2,0,1,1,34518.401200,4073114,0.0
1630698351,25.0,161.0,0,1,1,1,39880.863500,4063821,0.0
1630698348,19.0,161.0,1,2,2,1,13557.076000,4070749,0.0
1630698387,30.0,161.0,1,1,1,1,76891.125000,4076532,0.0
1630698390,57.0,161.0,1,1,1,1,86108.704000,4077351,0.0
1630698379,42.0,161.0,1,2,2,1,172660.824600,4071508,0.0
1630698364,23.0,161.0,1,1,2,1,27114.152000,4062076,1.0
1630698343,42.0,161.0,2,2,3,1,65566.043400,4058071,1.0
1630698359,18.0,161.0,1,1,1,1,88111.232000,4071713,0.0
1630698398,16.0,161.0,2,1,3,1,64613.440000,4072442,2.0
1630698383,46.0,161.0,1,1,2,1,36045.504000,4084528,1.0
1630698361,44.0,161.0,1,1,1,1,12302.580000,4070976,0.0
1630698392,51.0,161.0,1,1,1,1,48388.332800,4070631,0.0
1630698342,19.0,161.0,2,1,1,1,150233.160000,4071288,0.0
1630698377,17.0,161.0,3,0,1,1,135430.901500,4058160,0.0
1630698380,30.0,161.0,2,1,1,1,40851.571200,4082848,0.0
1630698344,50.0,161.0,4,1,1,1,77692.474000,4068934,0.0
1630698340,75.0,161.0,1,0,2,1,12316.937000,4055683,1.0
1630698357,46.0,161.0,1,1,1,1,53467.497600,4061943,0.0
1630698396,34.0,161.0,1,1,1,1,16153.360000,4070766,0.0
1630698376,73.0,161.0,1,0,2,1,43264.073000,4070477,1.0
1630698354,74.0,161.0,2,1,1,1,73103.925200,4072133,0.0

In [39]:
hlcm_vars

{'st_b_ln_building_sqft',
 'st_b_ln_non_residential_sqft',
 'st_b_ln_residential_units',
 'st_b_ln_sqft_per_unit',
 'st_building_age',
 'st_building_type_id_is_26',
 'st_building_type_id_is_83',
 'st_drv_nearest_grocery',
 'st_is_industrial',
 'st_is_medical',
 'st_is_office',
 'st_is_retail',
 'st_is_tcu',
 'st_jobs_within_30_min',
 'st_nodes_drv_log_sum_30min_jobs',
 'st_nodes_drv_log_sum_45min_jobs',
 'st_nodes_drv_log_sum_60min_jobs',
 'st_nodes_walk_ave_income',
 'st_nodes_walk_ave_unit_sqft',
 'st_nodes_walk_hhsize',
 'st_nodes_walk_ln_empden',
 'st_nodes_walk_ln_popden',
 'st_nodes_walk_log_sum_nonresidential_units',
 'st_nodes_walk_log_sum_residential_units',
 'st_nodes_walk_medical',
 'st_nodes_walk_midinc_hhs',
 'st_nodes_walk_percent_hh_with_children',
 'st_nodes_walk_percent_high_income',
 'st_nodes_walk_percent_low_income',
 'st_nodes_walk_percent_mid_income',
 'st_nodes_walk_percent_race1',
 'st_nodes_walk_percent_race2',
 'st_nodes_walk_percent_race4',
 'st_nodes_walk_quarter_mile_to_transit',
 'st_nodes_walk_residential',
 'st_parcels_ave_unit_size',
 'st_parcels_total_units',
 'st_sqft_per_unit',
 'st_sqft_price_nonres',
 'st_sqft_price_res',
 'st_stories',
 'st_walk_nearest_healthcenter',
 'st_zones_a_ln_emp_50min_transit',
 'st_zones_ln_empden_10',
 'st_zones_ln_empden_11',
 'st_zones_ln_empden_14',
 'st_zones_ln_empden_16',
 'st_zones_ln_empden_17',
 'st_zones_ln_empden_2',
 'st_zones_ln_empden_3',
 'st_zones_ln_empden_4',
 'st_zones_ln_empden_5',
 'st_zones_ln_empden_6',
 'st_zones_ln_empden_8',
 'st_zones_ln_empden_9',
 'st_zones_population',
 'st_zones_transit_jobs_30min',
 'st_zones_transit_jobs_50min'}